### ISSUE TITLE
save error without file extension

### ISSUE THREAD

**Issue by fastrizwaan** [obiwankennedy/HotShots#11]
Could you please Suffix image (.bmp, .jpg, .png) whatever selected in the file save dialog, so that this error goes away?
![Peek 2021-03-10 10-26](https://user-images.githubusercontent.com/1161682/110578593-2d935680-818b-11eb-9298-75b70dcfe6a5.gif)

**Comment by fastrizwaan** [comment]
compile fails with the commit https://github.com/obiwankennedy/HotShots/commit/13e583be6e5d648d1a2621f353e883abafe5fa46

```
src/AboutDialog.cpp: In member function ‘void AboutDialog::updateInfosImageFormats()’:
src/AboutDialog.cpp:192:76: error: conversion from ‘QHash<QString, QString>’ to non-scalar type ‘QMap<QString, QString>’ requested
  192 |     QMap<QString, QString> longFormats = MiscFunctions::getLongImageFormats();
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/bin/moc -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB --include /run/build/HotShots/release/moc_predefs.h -I/usr/lib/mkspecs/linux-g++ -I/run/build/HotShots -I/run/build/HotShots/src/3rdparty/qkeysequencewidget -I/run/build/HotShots/src/3rdparty/QSgml -I/run/build/HotShots/src/3rdparty/wwWidgets -I/run/build/HotShots/src/3rdparty/qt-json -I/run/build/HotShots/src/3rdparty/qxt -I/run/build/HotShots/src/uploaders -I/run/build/HotShots/src/editor -I/run/build/HotShots/src/editor/items -I/run/build/HotShots/src/editor/widgets -I/run/build/HotShots/src/editor/io -I/run/build/HotShots/src -I/usr/include/qxt/QxtGui -I/usr/include/qxt/QxtCore -I/usr/include/QxtGui -I/usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -I/usr/include/QtPrintSupport -I/usr/include/QtWidgets -I/usr/include/QtMultimedia -I/usr/include/QtX11Extras -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/editor/items/EditorImageItem.h -o release/moc_EditorImageItem.cpp
/usr/bin/moc -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB --include /run/build/HotShots/release/moc_predefs.h -I/usr/lib/mkspecs/linux-g++ -I/run/build/HotShots -I/run/build/HotShots/src/3rdparty/qkeysequencewidget -I/run/build/HotShots/src/3rdparty/QSgml -I/run/build/HotShots/src/3rdparty/wwWidgets -I/run/build/HotShots/src/3rdparty/qt-json -I/run/build/HotShots/src/3rdparty/qxt -I/run/build/HotShots/src/uploaders -I/run/build/HotShots/src/editor -I/run/build/HotShots/src/editor/items -I/run/build/HotShots/src/editor/widgets -I/run/build/HotShots/src/editor/io -I/run/build/HotShots/src -I/usr/include/qxt/QxtGui -I/usr/include/qxt/QxtCore -I/usr/include/QxtGui -I/usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -I/usr/include/QtPrintSupport -I/usr/include/QtWidgets -I/usr/include/QtMultimedia -I/usr/include/QtX11Extras -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/editor/items/EditorHighlighterItem.h -o release/moc_EditorHighlighterItem.cpp
/usr/bin/moc -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB --include /run/build/HotShots/release/moc_predefs.h -I/usr/lib/mkspecs/linux-g++ -I/run/build/HotShots -I/run/build/HotShots/src/3rdparty/qkeysequencewidget -I/run/build/HotShots/src/3rdparty/QSgml -I/run/build/HotShots/src/3rdparty/wwWidgets -I/run/build/HotShots/src/3rdparty/qt-json -I/run/build/HotShots/src/3rdparty/qxt -I/run/build/HotShots/src/uploaders -I/run/build/HotShots/src/editor -I/run/build/HotShots/src/editor/items -I/run/build/HotShots/src/editor/widgets -I/run/build/HotShots/src/editor/io -I/run/build/HotShots/src -I/usr/include/qxt/QxtGui -I/usr/include/qxt/QxtCore -I/usr/include/QxtGui -I/usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -I/usr/include/QtPrintSupport -I/usr/include/QtWidgets -I/usr/include/QtMultimedia -I/usr/include/QtX11Extras -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/editor/items/EditorEncircleItem.h -o release/moc_EditorEncircleItem.cpp
/usr/bin/moc -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB --include /run/build/HotShots/release/moc_predefs.h -I/usr/lib/mkspecs/linux-g++ -I/run/build/HotShots -I/run/build/HotShots/src/3rdparty/qkeysequencewidget -I/run/build/HotShots/src/3rdparty/QSgml -I/run/build/HotShots/src/3rdparty/wwWidgets -I/run/build/HotShots/src/3rdparty/qt-json -I/run/build/HotShots/src/3rdparty/qxt -I/run/build/HotShots/src/uploaders -I/run/build/HotShots/src/editor -I/run/build/HotShots/src/editor/items -I/run/build/HotShots/src/editor/widgets -I/run/build/HotShots/src/editor/io -I/run/build/HotShots/src -I/usr/include/qxt/QxtGui -I/usr/include/qxt/QxtCore -I/usr/include/QxtGui -I/usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -I/usr/include/QtPrintSupport -I/usr/include/QtWidgets -I/usr/include/QtMultimedia -I/usr/include/QtX11Extras -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/editor/items/EditorEllipseItem.h -o release/moc_EditorEllipseItem.cpp
/usr/bin/moc -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB --include /run/build/HotShots/release/moc_predefs.h -I/usr/lib/mkspecs/linux-g++ -I/run/build/HotShots -I/run/build/HotShots/src/3rdparty/qkeysequencewidget -I/run/build/HotShots/src/3rdparty/QSgml -I/run/build/HotShots/src/3rdparty/wwWidgets -I/run/build/HotShots/src/3rdparty/qt-json -I/run/build/HotShots/src/3rdparty/qxt -I/run/build/HotShots/src/uploaders -I/run/build/HotShots/src/editor -I/run/build/HotShots/src/editor/items -I/run/build/HotShots/src/editor/widgets -I/run/build/HotShots/src/editor/io -I/run/build/HotShots/src -I/usr/include/qxt/QxtGui -I/usr/include/qxt/QxtCore -I/usr/include/QxtGui -I/usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -I/usr/include/QtPrintSupport -I/usr/include/QtWidgets -I/usr/include/QtMultimedia -I/usr/include/QtX11Extras -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/editor/items/EditorCurveItem.h -o release/moc_EditorCurveItem.cpp
/usr/bin/moc -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB --include /run/build/HotShots/release/moc_predefs.h -I/usr/lib/mkspecs/linux-g++ -I/run/build/HotShots -I/run/build/HotShots/src/3rdparty/qkeysequencewidget -I/run/build/HotShots/src/3rdparty/QSgml -I/run/build/HotShots/src/3rdparty/wwWidgets -I/run/build/HotShots/src/3rdparty/qt-json -I/run/build/HotShots/src/3rdparty/qxt -I/run/build/HotShots/src/uploaders -I/run/build/HotShots/src/editor -I/run/build/HotShots/src/editor/items -I/run/build/HotShots/src/editor/widgets -I/run/build/HotShots/src/editor/io -I/run/build/HotShots/src -I/usr/include/qxt/QxtGui -I/usr/include/qxt/QxtCore -I/usr/include/QxtGui -I/usr/include/QxtCore -I/usr/local/Qxt/include/QxtGui -I/usr/local/Qxt/include/QxtCore -I/usr/include/QtPrintSupport -I/usr/include/QtWidgets -I/usr/include/QtMultimedia -I/usr/include/QtX11Extras -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/editor/items/EditorCropItem.h -o release/moc_EditorCropItem.cpp
make[1]: *** [Makefile.Release:1763: release/AboutDialog.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/run/build/HotShots'
make: *** [Makefile:52: release-install] Error 2
Error: module HotShots: Child process exited with code 2
```
